# Generated by Django 4.0.6 on 2022-08-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=8, verbose_name='股票名')),
                ('Rank', models.SmallIntegerField(verbose_name='排名')),
                ('Change', models.SmallIntegerField(verbose_name='排名变化')),
                ('Concept', models.CharField(max_length=32, verbose_name='概念')),
                ('Popularity', models.FloatField(verbose_name='人气')),
                ('Express', models.CharField(max_length=16, null=True, verbose_name='表现')),
                ('Time', models.DateTimeField(auto_now=True, verbose_name='时间')),
            ],
            options={
                'db_table': 'hotstocks',
            },
        ),
    ]
