# Generated by Django 4.0.6 on 2022-08-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitupStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=8, verbose_name='股票名')),
                ('Code', models.CharField(max_length=8, verbose_name='股票代码')),
                ('Latest', models.FloatField(verbose_name='涨停价')),
                ('Currency_value', models.FloatField(verbose_name='流通值')),
                ('Reason_type', models.CharField(max_length=32, verbose_name='涨停原因')),
                ('Limitup_type', models.CharField(max_length=8, verbose_name='涨停形态')),
                ('High_days', models.CharField(max_length=8, verbose_name='几天几板')),
                ('Change_rate', models.FloatField(verbose_name='换手率')),
            ],
            options={
                'db_table': 'limitupstocks',
            },
        ),
    ]
