# Generated by Django 4.0.6 on 2022-10-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitupstocks',
            name='Industry',
            field=models.CharField(max_length=8, null=True, verbose_name='申万行业'),
        ),
    ]
