# Generated by Django 4.0.6 on 2022-10-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_limitupstocks_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitupstocks',
            name='Industry',
        ),
    ]
