# Generated by Django 4.0.6 on 2022-08-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_limitupstocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitupstocks',
            name='Date',
            field=models.DateTimeField(auto_now=True, verbose_name='日期'),
        ),
    ]
