# Generated by Django 4.0.6 on 2022-08-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_limitupstocks_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitupstocks',
            name='High_days',
            field=models.CharField(max_length=8, null=True, verbose_name='几天几板'),
        ),
    ]
