# Generated by Django 4.0.6 on 2022-08-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_limitupstocks_high_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitupstocks',
            name='Change_rate',
            field=models.CharField(max_length=8, verbose_name='换手率'),
        ),
        migrations.AlterField(
            model_name='limitupstocks',
            name='Currency_value',
            field=models.IntegerField(verbose_name='流通值'),
        ),
    ]
