# Generated by Django 4.0.6 on 2022-08-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_firstboardstretagy_securities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptStretagy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='股票名称')),
                ('code', models.CharField(max_length=16, verbose_name='股票代码')),
                ('concept', models.CharField(max_length=32, verbose_name='概念')),
                ('last_price', models.FloatField(verbose_name='最新价')),
                ('increase', models.CharField(max_length=8, verbose_name='近1周涨幅')),
            ],
            options={
                'db_table': 'conceptstretagy',
            },
        ),
    ]
